### PR TITLE
[Task#66177] Init

### PR DESCRIPTION
**Pull request by Bui-Cong-Tri**
## Related Tickets:
- [#Ticket ID](https://edu-redmine.sun-asterisk.vn/issues/66176)

## WHAT this PR does?
- Initialize project

## Notes Impacted Areas:
- N/A.

## Attachments:
- N/A

### CODE REVIEW

**Comment by Bui-Cong-Tri** [comment]
Ready

**Review by ghost — COMMENTED** [review]
https://github.com/framgia/Training-Guideline/blob/master/Laravel/project1.md

**Comment by Bui-Cong-Tri** [comment]
Ready

**Review by ghost — COMMENTED** [review]
public css js ignore.

**Comment by Bui-Cong-Tri** [comment]
Ready

**Review by ghost — APPROVED** [review]

**Pull request merged**
